# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='huzaifa', max_length=30)),
                ('last_name', models.CharField(default='faruqui', max_length=40)),
                ('age', models.IntegerField(default='20')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='huzaifa', max_length=30)),
                ('last_name', models.CharField(default='faruqui', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(default='pictures/movie2.jpg', upload_to='pic_folder/')),
                ('duration', models.DurationField()),
                ('actors', models.ManyToManyField(to='home.Actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Director')),
            ],
        ),
    ]
