# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161031_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'ACTION'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE'), ('thriller', 'THRILLER'), ('drama', 'DRAMA')], default='drama', max_length=30),
        ),
    ]
